driver = 'SQL Server'
server = 'sql2019sd.company.com'
database = 'MySamm'
username = 'Salsify'
password = 'Fakepwd'
cnn_string= f'Driver={driver};Server={server};Database={database};UID={username}; PWD={password}'
